# Generated by Django 5.2.13 on 2026-04-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GitActions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pullrequest',
            old_name='description',
            new_name='code',
        ),
    ]
